version: '3.2'
services:
    postgres:
        image: postgres:9.6
        env_file:
            - ./env/.postgres-env
        ports:
            - "5432:5432"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
